--------------------------------------------------------
-- Archivo creado  - viernes-diciembre-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for View JUGADORES_SALARIO_ALTO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "LA LIGA"."JUGADORES_SALARIO_ALTO" ("NOMBRE", "APELLIDO", "EQUIPO") AS 
  SELECT
  j.NOMBRE,
  j.APELLIDOS,
  e.equipo_id
  
FROM
  JUGADORES j,
  EQUIPOS e

WHERE j.equipo_id = e.equipo_id
  AND SUELDO > 2000 
WITH READ ONLY;
--------------------------------------------------------
--  DDL for Table AFICION
--------------------------------------------------------

  CREATE TABLE "LA LIGA"."AFICION" 
   (	"AFICION" NUMBER, 
	"NOMBREGUERRA" VARCHAR2(40 BYTE), 
	"EQUIPO_ID" NUMBER(2,0), 
	"PEÑAS" VARCHAR2(35 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table AFICIONADOS
--------------------------------------------------------

  CREATE TABLE "LA LIGA"."AFICIONADOS" 
   (	"AFICIONADO_ID" NUMBER(9,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DNI" VARCHAR2(20 BYTE), 
	"FECHANACIMIENTO" DATE, 
	"AFICION" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CANTICOS
--------------------------------------------------------

  CREATE TABLE "LA LIGA"."CANTICOS" 
   (	"CANTICOS_ID" NUMBER(20,0), 
	"CANCIONES" VARCHAR2(30 BYTE), 
	"AFICION_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EQUIPOS
--------------------------------------------------------

  CREATE TABLE "LA LIGA"."EQUIPOS" 
   (	"EQUIPO_ID" NUMBER, 
	"NOMBRE" VARCHAR2(40 BYTE), 
	"FECHAFUNDACION" DATE, 
	"COLORES" VARCHAR2(20 BYTE), 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "LA LIGA"."EQUIPOS"."EQUIPO_ID" IS 'Clave primaria';
   COMMENT ON COLUMN "LA LIGA"."EQUIPOS"."NOMBRE" IS 'Nombre del equipo';
   COMMENT ON COLUMN "LA LIGA"."EQUIPOS"."FECHAFUNDACION" IS 'Fecha de Fundacion del Equipo';
   COMMENT ON COLUMN "LA LIGA"."EQUIPOS"."COLORES" IS 'Colores de las camisetas';
--------------------------------------------------------
--  DDL for Table ESTADIO
--------------------------------------------------------

  CREATE TABLE "LA LIGA"."ESTADIO" 
   (	"ESTADIO_ID" NUMBER(2,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"CIUDAD" VARCHAR2(20 BYTE), 
	"AFORO" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JUGADORES
--------------------------------------------------------

  CREATE TABLE "LA LIGA"."JUGADORES" 
   (	"JUGADORES_ID" NUMBER(4,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDOS" VARCHAR2(35 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE), 
	"SUELDO" NUMBER(7,0), 
	"EQUIPO_ID" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOMBREGUERRA
--------------------------------------------------------

  CREATE TABLE "LA LIGA"."NOMBREGUERRA" 
   (	"NOMBREGUERRA_ID" VARCHAR2(100 BYTE), 
	"TITULOS" VARCHAR2(100 BYTE), 
	"AFICION_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Sequence DEPARTMENTS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LA LIGA"."DEPARTMENTS_SEQ"  MINVALUE 1 MAXVALUE 9990 INCREMENT BY 10 START WITH 280 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEES_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LA LIGA"."EMPLOYEES_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 207 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOCATIONS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "LA LIGA"."LOCATIONS_SEQ"  MINVALUE 1 MAXVALUE 9900 INCREMENT BY 100 START WITH 3300 NOCACHE  NOORDER  NOCYCLE ;
REM INSERTING into "LA LIGA".AFICION
SET DEFINE OFF;
Insert into "LA LIGA".AFICION (AFICION,NOMBREGUERRA,EQUIPO_ID,"PEÑAS") values ('1','LOS GRANDES','1','LOS DEL SUR');
Insert into "LA LIGA".AFICION (AFICION,NOMBREGUERRA,EQUIPO_ID,"PEÑAS") values ('2','LG','2','WEST');
REM INSERTING into "LA LIGA".AFICIONADOS
SET DEFINE OFF;
Insert into "LA LIGA".AFICIONADOS (AFICIONADO_ID,NOMBRE,DNI,FECHANACIMIENTO,AFICION) values ('1','PEPE','55454544-U',to_date('16/12/67','DD/MM/RR'),'1');
Insert into "LA LIGA".AFICIONADOS (AFICIONADO_ID,NOMBRE,DNI,FECHANACIMIENTO,AFICION) values ('2','LUIS','45698523-T',to_date('21/12/46','DD/MM/RR'),'2');
REM INSERTING into "LA LIGA".CANTICOS
SET DEFINE OFF;
Insert into "LA LIGA".CANTICOS (CANTICOS_ID,CANCIONES,AFICION_ID) values ('1','VICTORIA','1');
Insert into "LA LIGA".CANTICOS (CANTICOS_ID,CANCIONES,AFICION_ID) values ('2','GANAR GANAR','1');
REM INSERTING into "LA LIGA".EQUIPOS
SET DEFINE OFF;
Insert into "LA LIGA".EQUIPOS (EQUIPO_ID,NOMBRE,FECHAFUNDACION,COLORES,AFICION_ID) values ('1','LOS PIEDRAS',to_date('19/12/14','DD/MM/RR'),'ROJO/VERDE','1');
Insert into "LA LIGA".EQUIPOS (EQUIPO_ID,NOMBRE,FECHAFUNDACION,COLORES,AFICION_ID) values ('2','LOS VERDES',to_date('20/12/13','DD/MM/RR'),'VERDE','2');
Insert into "LA LIGA".EQUIPOS (EQUIPO_ID,NOMBRE,FECHAFUNDACION,COLORES,AFICION_ID) values ('3','LOS AMARILLOS',to_date('24/12/10','DD/MM/RR'),'AMARILLO','3');
REM INSERTING into "LA LIGA".ESTADIO
SET DEFINE OFF;
Insert into "LA LIGA".ESTADIO (ESTADIO_ID,NOMBRE,CIUDAD,AFORO) values ('1','PRIMERO','ESTA','5000');
Insert into "LA LIGA".ESTADIO (ESTADIO_ID,NOMBRE,CIUDAD,AFORO) values ('2','SEGUNDO','AQUEL','60000');
Insert into "LA LIGA".ESTADIO (ESTADIO_ID,NOMBRE,CIUDAD,AFORO) values ('3','TERCERO','ESTA','56595');
REM INSERTING into "LA LIGA".JUGADORES
SET DEFINE OFF;
Insert into "LA LIGA".JUGADORES (JUGADORES_ID,NOMBRE,APELLIDOS,TELEFONO,SUELDO,EQUIPO_ID) values ('1','LUIS','ANDRES','546545','2001','1');
Insert into "LA LIGA".JUGADORES (JUGADORES_ID,NOMBRE,APELLIDOS,TELEFONO,SUELDO,EQUIPO_ID) values ('2','PEPE','ANDANDO','1418464','655','1');
REM INSERTING into "LA LIGA".NOMBREGUERRA
SET DEFINE OFF;
Insert into "LA LIGA".NOMBREGUERRA (NOMBREGUERRA_ID,TITULOS,AFICION_ID) values ('LOS MALOTES','LOS INCREIBLES','1');
Insert into "LA LIGA".NOMBREGUERRA (NOMBREGUERRA_ID,TITULOS,AFICION_ID) values ('LOS GRACIOSOS','FUNNY','2');
--------------------------------------------------------
--  DDL for Index EQUIPOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LA LIGA"."EQUIPOS_PK" ON "LA LIGA"."EQUIPOS" ("EQUIPO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index NOMBREGUERRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LA LIGA"."NOMBREGUERRA_PK" ON "LA LIGA"."NOMBREGUERRA" ("NOMBREGUERRA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CANTICOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LA LIGA"."CANTICOS_PK" ON "LA LIGA"."CANTICOS" ("CANTICOS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AFICION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LA LIGA"."AFICION_PK" ON "LA LIGA"."AFICION" ("AFICION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTADIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LA LIGA"."ESTADIO_PK" ON "LA LIGA"."ESTADIO" ("ESTADIO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index AFICIONADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LA LIGA"."AFICIONADOS_PK" ON "LA LIGA"."AFICIONADOS" ("AFICIONADO_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JUGADORES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "LA LIGA"."JUGADORES_PK" ON "LA LIGA"."JUGADORES" ("JUGADORES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Procedure ADD_JOB_HISTORY
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "LA LIGA"."ADD_JOB_HISTORY" 
  (  p_emp_id          job_history.employee_id%type
   , p_start_date      job_history.start_date%type
   , p_end_date        job_history.end_date%type
   , p_job_id          job_history.job_id%type
   , p_department_id   job_history.department_id%type
   )
IS
BEGIN
  INSERT INTO job_history (employee_id, start_date, end_date,
                           job_id, department_id)
    VALUES(p_emp_id, p_start_date, p_end_date, p_job_id, p_department_id);
END add_job_history;

/
--------------------------------------------------------
--  DDL for Procedure SECURE_DML
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "LA LIGA"."SECURE_DML" 
IS
BEGIN
  IF TO_CHAR (SYSDATE, 'HH24:MI') NOT BETWEEN '08:00' AND '18:00'
        OR TO_CHAR (SYSDATE, 'DY') IN ('SAT', 'SUN') THEN
	RAISE_APPLICATION_ERROR (-20205,
		'You may only make changes during normal office hours');
  END IF;
END secure_dml;

/
--------------------------------------------------------
--  Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."AFICION" MODIFY ("AFICION" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."AFICION" MODIFY ("NOMBREGUERRA" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."AFICION" ADD CONSTRAINT "AFICION_PK" PRIMARY KEY ("AFICION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LA LIGA"."AFICION" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADIO
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."ESTADIO" MODIFY ("ESTADIO_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."ESTADIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."ESTADIO" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."ESTADIO" ADD CONSTRAINT "ESTADIO_PK" PRIMARY KEY ("ESTADIO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOMBREGUERRA
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."NOMBREGUERRA" MODIFY ("NOMBREGUERRA_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."NOMBREGUERRA" MODIFY ("TITULOS" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."NOMBREGUERRA" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."NOMBREGUERRA" ADD CONSTRAINT "NOMBREGUERRA_PK" PRIMARY KEY ("NOMBREGUERRA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."JUGADORES" MODIFY ("JUGADORES_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."JUGADORES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."JUGADORES" MODIFY ("APELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."JUGADORES" MODIFY ("SUELDO" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."JUGADORES" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."JUGADORES" ADD CONSTRAINT "JUGADORES_PK" PRIMARY KEY ("JUGADORES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."EQUIPOS" MODIFY ("EQUIPO_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."EQUIPOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."EQUIPOS" MODIFY ("FECHAFUNDACION" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."EQUIPOS" ADD CONSTRAINT "EQUIPOS_PK" PRIMARY KEY ("EQUIPO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LA LIGA"."EQUIPOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AFICIONADOS
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."AFICIONADOS" MODIFY ("AFICIONADO_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."AFICIONADOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."AFICIONADOS" MODIFY ("DNI" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."AFICIONADOS" MODIFY ("FECHANACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."AFICIONADOS" ADD CONSTRAINT "AFICIONADOS_PK" PRIMARY KEY ("AFICIONADO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LA LIGA"."AFICIONADOS" MODIFY ("AFICION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."CANTICOS" MODIFY ("CANTICOS_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."CANTICOS" MODIFY ("CANCIONES" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."CANTICOS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "LA LIGA"."CANTICOS" ADD CONSTRAINT "CANTICOS_PK" PRIMARY KEY ("CANTICOS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFICION
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."AFICION" ADD CONSTRAINT "EQUIPOS_FK" FOREIGN KEY ("EQUIPO_ID")
	  REFERENCES "LA LIGA"."EQUIPOS" ("EQUIPO_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AFICIONADOS
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."AFICIONADOS" ADD CONSTRAINT "AFICION_FK1" FOREIGN KEY ("AFICIONADO_ID")
	  REFERENCES "LA LIGA"."AFICION" ("AFICION") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CANTICOS
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."CANTICOS" ADD CONSTRAINT "AFICION_FK2" FOREIGN KEY ("AFICION_ID")
	  REFERENCES "LA LIGA"."AFICION" ("AFICION") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EQUIPOS
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."EQUIPOS" ADD CONSTRAINT "ESTADIO_FK" FOREIGN KEY ("EQUIPO_ID")
	  REFERENCES "LA LIGA"."ESTADIO" ("ESTADIO_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table JUGADORES
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."JUGADORES" ADD CONSTRAINT "EQUIPOS_FK2" FOREIGN KEY ("EQUIPO_ID")
	  REFERENCES "LA LIGA"."EQUIPOS" ("EQUIPO_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOMBREGUERRA
--------------------------------------------------------

  ALTER TABLE "LA LIGA"."NOMBREGUERRA" ADD CONSTRAINT "AFICION_FK" FOREIGN KEY ("AFICION_ID")
	  REFERENCES "LA LIGA"."AFICION" ("AFICION") ON DELETE CASCADE ENABLE;
